# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks. 
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1
  codecov: codecov/codecov@1.2.1
  cypress: cypress-io/cypress@1.28.0

  stackhawk: stackhawk/stackhawk@1.0.2


jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  lint:  
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/node
    docker:
      - image: cimg/node:15.1
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
    steps:
      # Checkout the code as the first step.
      - checkout
      # Next, the node orb's install-packages step will install the dependencies from a package.json.
      # The orb install-packages step will also automatically cache them for faster future runs.
      - node/install-packages:
          pkg-manager: yarn
      # If you are using yarn instead npm, remove the line above and uncomment the two lines below.
      - run:
          name: Check Styling
          command: yarn check-styling
  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: build
          command: yarn build
  deploy:
    docker:
      - image: cimg/node:15.1
    steps:
      - run:
          name: deploy
          command: curl https://api.render.com/deploy/srv-c2qipjb2v8p1q1jmcom0?key=PDeA5VT8bdQ


workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  sample: 
    jobs:
      - lint
      - build:
          requires:
            - lint
      - cypress/install:
          yarn: true
      - cypress/run:
            executor: cypress/browsers-chrome77
            browser: chrome
            start: npx pm2 --name idea-factory start npm -- start
            wait-on: '-c ./wo-config.js'
            spec: '**/idea-factory/**'
            post-steps:
              - codecov/upload:
                  file: ./coverage/lcov.info
            requires:
              - cypress/install
            attach-workspace: true
      - deploy:
          requires:
            - build
            - cypress/run
      - stackhawk/hawkscan-remote:
          configuration-files: stackhawk.yml
          host: 'https://beta.idea-factory.co'
          requires:
            - deploy